import { Poppins } from "next/font/google";
import Head from "next/head";
import TakeQuizButton from "@/components/take_quiz_button";
import styles from "@/styles/home_styles.module.css";
import AnswerQuiz from "@/components/answer_quiz";
import { useState } from "react";
import QuizResult from "@/components/quiz_result";

const poppins = Poppins({ subsets: ["latin"], weight: "400" });
export default function Home() {
	const [content, setContent] = useState("");

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<meta
					name="viewport"
					content="width=device-width, initial-scale=1"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main className={[styles.home, poppins]}>
				<div className={[styles.app_container]}>
					<div className="flex_col">
						<div className="container">
							<TakeQuizButton
								onClick={() => setContent("show-quiz")}
							/>
						</div>
						<div className="container">
							{content === "show-quiz" && (
								<AnswerQuiz
									question={"Lorem text from nowhere?"}
								/>
							)}
							{content === "show-result" && <QuizResult />}
							{!content && (
								<p className="text">
									Welcome to the Quiz App! Click the button
									above to take a quiz.
								</p>
							)}
						</div>
					</div>
				</div>
			</main>
		</>
	);
}
